export const SESSION_KEY_OPTIMISTIC_UPDATES = 'MSW_OPTIMISTIC_UPDATES';
export const SESSION_KEY_TODO = 'MSW_TODO';
export const LOCAL_KEY_GOOGLE_MAPS_API = 'MSW_GOOGLE_MAPS_API';
export const LOCAL_KEY_GOOGLE_MAPS_API_SAVE = 'MSW_GOOGLE_MAPS_API_SAVE';
